### PR TITLE
[OLED][I2C] created initialization sequence based on doc, link in code

### PR DESCRIPTION
**Pull request by lolconnor1**
made an init sequence based on what I found in the doc, idk if it works for our specific application.

### CODE REVIEW

**Comment by leroymusa** [comment]
Could you link where you found the sequence? It doesn't look totally accurate as `SET_DISPLAY_OFF ` should be the first write command in the boot up process.

**Comment by leroymusa** [comment]
Try seeing the doc if it fits this format, ngl it's a bit confusing

```
// set_display_off
// set_display_clock_divide_ratio
// oscillator_frequency
// set_multiplex_ratio
// set_display_offset
// set_start_line
// charge_pump_setting
// memory_addressing_mode
// segment_re-map
// com_output_scan_direction
// com_pins_hardware_configuration
// set_contrast_control
// set_pre-charge_period
// set_vcomh_deselect_level
// entire_display_on
// normal_display_mode
// set_display_on

```

**Comment by lolconnor1** [comment]
got it from the doc you gave me for the command table [here, page 64](https://cdn-shop.adafruit.com/datasheets/SSD1306.pdf)

**Comment by leroymusa** [comment]
Ah, the command tables aren't sequential. I don't see page 64.

**Comment by lolconnor1** [comment]
made some changes

**Comment by leroymusa** [comment]
This looks good! 
Yes, `0x12` is recommended for the 128x64 we are using.

**Pull request merged**
